version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "21:00"
    labels:
      - "dependabot"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "sunday"
      time: "21:00"
    labels:
      - "dependabot"
