name: "Development: Update, Build & Deploy"
run-name: Deploy ${{ github.repository }} to development by @${{ github.actor }}

on:
    workflow_dispatch:
    push:
        branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  development-build-deploy:
    uses: s-Cube-Enterprise/reusable-workflows/.github/workflows/jib-build-publish.yaml@main
    with:
      AWS_REGION: us-east-1
      ECR_REPOSITORY: sandf-service_document
      EKS_DEPLOYMENT: scube-document-service-depl
      EKS_CONTAINER: scube-document-service
      KUBE_NAMESPACE: s-and-f
      IMAGE_TAG: latest
      JAVA_VERSION: 21
      TARGET_ENVIRONMENT: development
    secrets: inherit
